from pubsub_to_firebase_functions import lightswitches_pubsub_to_firebase
from firebase_on_update_function import firestore_on_update_to_devices_pubsub

lightswitches_pubsub_to_firebase("None", None)
firestore_on_update_to_devices_pubsub("None", None)
